version = 1

[schema]

[[schema.tables]]
id = 0
name = "users"
primary_key = { columns = [{ table = 0, index = 0 }], index = { table = 0, index = 0 } }

[[schema.tables.columns]]
id = { table = 0, index = 0 }
name = "id"
ty = "Uuid"
storage_ty = "Uuid"

[[schema.tables.columns]]
id = { table = 0, index = 1 }
name = "username"
ty = "String"
storage_ty = "Text"

[[schema.tables.columns]]
id = { table = 0, index = 2 }
name = "email"
ty = "String"
storage_ty = "Text"

[[schema.tables.columns]]
id = { table = 0, index = 3 }
name = "email_verified"
ty = "Bool"
storage_ty = "Boolean"

[[schema.tables.columns]]
id = { table = 0, index = 4 }
name = "password_hash"
ty = "String"
storage_ty = "Text"

[[schema.tables.columns]]
id = { table = 0, index = 5 }
name = "date_created"
ty = "DateTime"
storage_ty = { DateTime = 6 }

[[schema.tables.columns]]
id = { table = 0, index = 6 }
name = "date_updated"
ty = "DateTime"
storage_ty = { DateTime = 6 }

[[schema.tables.columns]]
id = { table = 0, index = 7 }
name = "date_joined"
ty = "DateTime"
storage_ty = { DateTime = 6 }

[[schema.tables.indices]]
id = { table = 0, index = 0 }
name = "index_users_by_id"
on = 0
columns = [{ column = { table = 0, index = 0 }, op = "Eq", scope = "Partition" }]
unique = true
primary_key = true

[[schema.tables.indices]]
id = { table = 0, index = 1 }
name = "index_users_by_email"
on = 0
columns = [{ column = { table = 0, index = 2 }, op = "Eq", scope = "Partition" }]
unique = true

[[schema.tables]]
id = 1
name = "tasks"
primary_key = { columns = [{ table = 1, index = 0 }], index = { table = 1, index = 0 } }

[[schema.tables.columns]]
id = { table = 1, index = 0 }
name = "id"
ty = "Uuid"
storage_ty = "Uuid"

[[schema.tables.columns]]
id = { table = 1, index = 1 }
name = "user_id"
ty = "Uuid"
storage_ty = "Uuid"

[[schema.tables.columns]]
id = { table = 1, index = 2 }
name = "name"
ty = "String"
storage_ty = "Text"

[[schema.tables.columns]]
id = { table = 1, index = 3 }
name = "description"
ty = "String"
storage_ty = "Text"
nullable = true

[[schema.tables.columns]]
id = { table = 1, index = 4 }
name = "endpoint"
ty = "String"
storage_ty = "Text"

[[schema.tables.columns]]
id = { table = 1, index = 5 }
name = "method"
ty = "String"
storage_ty = "Text"

[[schema.tables.columns]]
id = { table = 1, index = 6 }
name = "result_schema"
ty = "String"
storage_ty = "Text"
nullable = true

[[schema.tables.columns]]
id = { table = 1, index = 7 }
name = "body"
ty = "String"
storage_ty = "Text"
nullable = true

[[schema.tables.columns]]
id = { table = 1, index = 8 }
name = "date_created"
ty = "DateTime"
storage_ty = { DateTime = 6 }

[[schema.tables.columns]]
id = { table = 1, index = 9 }
name = "date_updated"
ty = "DateTime"
storage_ty = { DateTime = 6 }

[[schema.tables.indices]]
id = { table = 1, index = 0 }
name = "index_tasks_by_id"
on = 1
columns = [{ column = { table = 1, index = 0 }, op = "Eq", scope = "Partition" }]
unique = true
primary_key = true

[[schema.tables.indices]]
id = { table = 1, index = 1 }
name = "index_tasks_by_user_id"
on = 1
columns = [{ column = { table = 1, index = 1 }, op = "Eq", scope = "Partition" }]

[[schema.tables]]
id = 2
name = "workflow_tasks"
primary_key = { columns = [{ table = 2, index = 0 }], index = { table = 2, index = 0 } }

[[schema.tables.columns]]
id = { table = 2, index = 0 }
name = "id"
ty = "Uuid"
storage_ty = "Uuid"

[[schema.tables.columns]]
id = { table = 2, index = 1 }
name = "workflow_id"
ty = "Uuid"
storage_ty = "Uuid"

[[schema.tables.columns]]
id = { table = 2, index = 2 }
name = "task_id"
ty = "Uuid"
storage_ty = "Uuid"

[[schema.tables.columns]]
id = { table = 2, index = 3 }
name = "step_name"
ty = "String"
storage_ty = "Text"

[[schema.tables.columns]]
id = { table = 2, index = 4 }
name = "task_body"
ty = "String"
storage_ty = "Text"
nullable = true

[[schema.tables.columns]]
id = { table = 2, index = 5 }
name = "task_result_schema"
ty = "String"
storage_ty = "Text"
nullable = true

[[schema.tables.columns]]
id = { table = 2, index = 6 }
name = "run_position"
ty = "I32"
storage_ty = { Integer = 4 }

[[schema.tables.columns]]
id = { table = 2, index = 7 }
name = "retry_count"
ty = "I32"
storage_ty = { Integer = 4 }
nullable = true

[[schema.tables.columns]]
id = { table = 2, index = 8 }
name = "retry_delay_secs"
ty = "I32"
storage_ty = { Integer = 4 }
nullable = true

[[schema.tables.columns]]
id = { table = 2, index = 9 }
name = "date_created"
ty = "DateTime"
storage_ty = { DateTime = 6 }

[[schema.tables.columns]]
id = { table = 2, index = 10 }
name = "date_updated"
ty = "DateTime"
storage_ty = { DateTime = 6 }

[[schema.tables.indices]]
id = { table = 2, index = 0 }
name = "index_workflow_tasks_by_id"
on = 2
columns = [{ column = { table = 2, index = 0 }, op = "Eq", scope = "Partition" }]
unique = true
primary_key = true

[[schema.tables.indices]]
id = { table = 2, index = 1 }
name = "index_workflow_tasks_by_workflow_id_and_step_name"
on = 2
columns = [{ column = { table = 2, index = 1 }, op = "Eq", scope = "Partition" }, { column = { table = 2, index = 3 }, op = "Eq", scope = "Local" }]
unique = true

[[schema.tables.indices]]
id = { table = 2, index = 2 }
name = "index_workflow_tasks_by_workflow_id"
on = 2
columns = [{ column = { table = 2, index = 1 }, op = "Eq", scope = "Partition" }]

[[schema.tables.indices]]
id = { table = 2, index = 3 }
name = "index_workflow_tasks_by_task_id"
on = 2
columns = [{ column = { table = 2, index = 2 }, op = "Eq", scope = "Partition" }]

[[schema.tables]]
id = 3
name = "workflows"
primary_key = { columns = [{ table = 3, index = 0 }], index = { table = 3, index = 0 } }

[[schema.tables.columns]]
id = { table = 3, index = 0 }
name = "id"
ty = "Uuid"
storage_ty = "Uuid"

[[schema.tables.columns]]
id = { table = 3, index = 1 }
name = "user_id"
ty = "Uuid"
storage_ty = "Uuid"

[[schema.tables.columns]]
id = { table = 3, index = 2 }
name = "name"
ty = "String"
storage_ty = "Text"

[[schema.tables.columns]]
id = { table = 3, index = 3 }
name = "description"
ty = "String"
storage_ty = "Text"
nullable = true

[[schema.tables.columns]]
id = { table = 3, index = 4 }
name = "run_type"
ty = "String"
storage_ty = "Text"

[[schema.tables.columns]]
id = { table = 3, index = 5 }
name = "schedule_time"
ty = "DateTime"
storage_ty = { DateTime = 6 }
nullable = true

[[schema.tables.columns]]
id = { table = 3, index = 6 }
name = "cron_expression"
ty = "String"
storage_ty = "Text"
nullable = true

[[schema.tables.columns]]
id = { table = 3, index = 7 }
name = "cron_next_run"
ty = "DateTime"
storage_ty = { DateTime = 6 }
nullable = true

[[schema.tables.columns]]
id = { table = 3, index = 8 }
name = "is_active"
ty = "Bool"
storage_ty = "Boolean"

[[schema.tables.columns]]
id = { table = 3, index = 9 }
name = "date_created"
ty = "DateTime"
storage_ty = { DateTime = 6 }

[[schema.tables.columns]]
id = { table = 3, index = 10 }
name = "date_updated"
ty = "DateTime"
storage_ty = { DateTime = 6 }

[[schema.tables.indices]]
id = { table = 3, index = 0 }
name = "index_workflows_by_id"
on = 3
columns = [{ column = { table = 3, index = 0 }, op = "Eq", scope = "Partition" }]
unique = true
primary_key = true

[[schema.tables.indices]]
id = { table = 3, index = 1 }
name = "index_workflows_by_user_id"
on = 3
columns = [{ column = { table = 3, index = 1 }, op = "Eq", scope = "Partition" }]

[[schema.tables]]
id = 4
name = "workflow_task_edges"
primary_key = { columns = [{ table = 4, index = 0 }], index = { table = 4, index = 0 } }

[[schema.tables.columns]]
id = { table = 4, index = 0 }
name = "id"
ty = "Uuid"
storage_ty = "Uuid"

[[schema.tables.columns]]
id = { table = 4, index = 1 }
name = "workflow_id"
ty = "Uuid"
storage_ty = "Uuid"

[[schema.tables.columns]]
id = { table = 4, index = 2 }
name = "from_task_id"
ty = "Uuid"
storage_ty = "Uuid"

[[schema.tables.columns]]
id = { table = 4, index = 3 }
name = "to_task_id"
ty = "Uuid"
storage_ty = "Uuid"

[[schema.tables.columns]]
id = { table = 4, index = 4 }
name = "date_created"
ty = "DateTime"
storage_ty = { DateTime = 6 }

[[schema.tables.columns]]
id = { table = 4, index = 5 }
name = "date_updated"
ty = "DateTime"
storage_ty = { DateTime = 6 }

[[schema.tables.indices]]
id = { table = 4, index = 0 }
name = "index_workflow_task_edges_by_id"
on = 4
columns = [{ column = { table = 4, index = 0 }, op = "Eq", scope = "Partition" }]
unique = true
primary_key = true

[[schema.tables.indices]]
id = { table = 4, index = 1 }
name = "index_workflow_task_edges_by_workflow_id_and_from_task_id__5f9d"
on = 4
columns = [{ column = { table = 4, index = 1 }, op = "Eq", scope = "Partition" }, { column = { table = 4, index = 2 }, op = "Eq", scope = "Local" }, { column = { table = 4, index = 3 }, op = "Eq", scope = "Local" }]
unique = true

[[schema.tables.indices]]
id = { table = 4, index = 2 }
name = "index_workflow_task_edges_by_workflow_id"
on = 4
columns = [{ column = { table = 4, index = 1 }, op = "Eq", scope = "Partition" }]

[[schema.tables.indices]]
id = { table = 4, index = 3 }
name = "index_workflow_task_edges_by_from_task_id"
on = 4
columns = [{ column = { table = 4, index = 2 }, op = "Eq", scope = "Partition" }]

[[schema.tables.indices]]
id = { table = 4, index = 4 }
name = "index_workflow_task_edges_by_to_task_id"
on = 4
columns = [{ column = { table = 4, index = 3 }, op = "Eq", scope = "Partition" }]

[[schema.tables]]
id = 5
name = "workflow_states"
primary_key = { columns = [{ table = 5, index = 0 }], index = { table = 5, index = 0 } }

[[schema.tables.columns]]
id = { table = 5, index = 0 }
name = "id"
ty = "Uuid"
storage_ty = "Uuid"

[[schema.tables.columns]]
id = { table = 5, index = 1 }
name = "workflow_id"
ty = "Uuid"
storage_ty = "Uuid"

[[schema.tables.columns]]
id = { table = 5, index = 2 }
name = "status"
ty = "String"
storage_ty = "Text"

[[schema.tables.columns]]
id = { table = 5, index = 3 }
name = "start_time"
ty = "DateTime"
storage_ty = { DateTime = 6 }
nullable = true

[[schema.tables.columns]]
id = { table = 5, index = 4 }
name = "end_time"
ty = "DateTime"
storage_ty = { DateTime = 6 }
nullable = true

[[schema.tables.columns]]
id = { table = 5, index = 5 }
name = "date_created"
ty = "DateTime"
storage_ty = { DateTime = 6 }

[[schema.tables.columns]]
id = { table = 5, index = 6 }
name = "date_updated"
ty = "DateTime"
storage_ty = { DateTime = 6 }

[[schema.tables.indices]]
id = { table = 5, index = 0 }
name = "index_workflow_states_by_id"
on = 5
columns = [{ column = { table = 5, index = 0 }, op = "Eq", scope = "Partition" }]
unique = true
primary_key = true

[[schema.tables.indices]]
id = { table = 5, index = 1 }
name = "index_workflow_states_by_workflow_id"
on = 5
columns = [{ column = { table = 5, index = 1 }, op = "Eq", scope = "Partition" }]

[[schema.tables]]
id = 6
name = "workflow_task_states"
primary_key = { columns = [{ table = 6, index = 0 }], index = { table = 6, index = 0 } }

[[schema.tables.columns]]
id = { table = 6, index = 0 }
name = "id"
ty = "Uuid"
storage_ty = "Uuid"

[[schema.tables.columns]]
id = { table = 6, index = 1 }
name = "workflow_task_id"
ty = "Uuid"
storage_ty = "Uuid"

[[schema.tables.columns]]
id = { table = 6, index = 2 }
name = "workflow_state_id"
ty = "Uuid"
storage_ty = "Uuid"

[[schema.tables.columns]]
id = { table = 6, index = 3 }
name = "result"
ty = "String"
storage_ty = "Text"
nullable = true

[[schema.tables.columns]]
id = { table = 6, index = 4 }
name = "status"
ty = "String"
storage_ty = "Text"

[[schema.tables.columns]]
id = { table = 6, index = 5 }
name = "retry_attempts"
ty = "I32"
storage_ty = { Integer = 4 }

[[schema.tables.columns]]
id = { table = 6, index = 6 }
name = "callback_token"
ty = "String"
storage_ty = "Text"

[[schema.tables.columns]]
id = { table = 6, index = 7 }
name = "start_time"
ty = "DateTime"
storage_ty = { DateTime = 6 }
nullable = true

[[schema.tables.columns]]
id = { table = 6, index = 8 }
name = "end_time"
ty = "DateTime"
storage_ty = { DateTime = 6 }
nullable = true

[[schema.tables.columns]]
id = { table = 6, index = 9 }
name = "date_created"
ty = "DateTime"
storage_ty = { DateTime = 6 }

[[schema.tables.columns]]
id = { table = 6, index = 10 }
name = "date_updated"
ty = "DateTime"
storage_ty = { DateTime = 6 }

[[schema.tables.indices]]
id = { table = 6, index = 0 }
name = "index_workflow_task_states_by_id"
on = 6
columns = [{ column = { table = 6, index = 0 }, op = "Eq", scope = "Partition" }]
unique = true
primary_key = true

[[schema.tables.indices]]
id = { table = 6, index = 1 }
name = "index_workflow_task_states_by_workflow_task_id"
on = 6
columns = [{ column = { table = 6, index = 1 }, op = "Eq", scope = "Partition" }]

[[schema.tables.indices]]
id = { table = 6, index = 2 }
name = "index_workflow_task_states_by_workflow_state_id"
on = 6
columns = [{ column = { table = 6, index = 2 }, op = "Eq", scope = "Partition" }]

[[schema.tables.indices]]
id = { table = 6, index = 3 }
name = "index_workflow_task_states_by_callback_token"
on = 6
columns = [{ column = { table = 6, index = 6 }, op = "Eq", scope = "Partition" }]
unique = true

[[schema.tables]]
id = 7
name = "user_verifications"
primary_key = { columns = [{ table = 7, index = 0 }], index = { table = 7, index = 0 } }

[[schema.tables.columns]]
id = { table = 7, index = 0 }
name = "id"
ty = "I64"
storage_ty = { Integer = 8 }
auto_increment = true

[[schema.tables.columns]]
id = { table = 7, index = 1 }
name = "user_id"
ty = "Uuid"
storage_ty = "Uuid"

[[schema.tables.columns]]
id = { table = 7, index = 2 }
name = "code"
ty = "String"
storage_ty = "Text"

[[schema.tables.columns]]
id = { table = 7, index = 3 }
name = "expires_at"
ty = "DateTime"
storage_ty = { DateTime = 6 }

[[schema.tables.columns]]
id = { table = 7, index = 4 }
name = "date_created"
ty = "DateTime"
storage_ty = { DateTime = 6 }

[[schema.tables.columns]]
id = { table = 7, index = 5 }
name = "date_updated"
ty = "DateTime"
storage_ty = { DateTime = 6 }

[[schema.tables.indices]]
id = { table = 7, index = 0 }
name = "index_user_verifications_by_id"
on = 7
columns = [{ column = { table = 7, index = 0 }, op = "Eq", scope = "Partition" }]
unique = true
primary_key = true

[[schema.tables.indices]]
id = { table = 7, index = 1 }
name = "index_user_verifications_by_user_id"
on = 7
columns = [{ column = { table = 7, index = 1 }, op = "Eq", scope = "Partition" }]

[[schema.tables.indices]]
id = { table = 7, index = 2 }
name = "index_user_verifications_by_code"
on = 7
columns = [{ column = { table = 7, index = 2 }, op = "Eq", scope = "Partition" }]
unique = true

[[schema.tables]]
id = 8
name = "blacklisted_tokens"
primary_key = { columns = [{ table = 8, index = 0 }], index = { table = 8, index = 0 } }

[[schema.tables.columns]]
id = { table = 8, index = 0 }
name = "id"
ty = "I64"
storage_ty = { Integer = 8 }
auto_increment = true

[[schema.tables.columns]]
id = { table = 8, index = 1 }
name = "jti"
ty = "String"
storage_ty = "Text"

[[schema.tables.columns]]
id = { table = 8, index = 2 }
name = "token_type"
ty = "String"
storage_ty = "Text"

[[schema.tables.columns]]
id = { table = 8, index = 3 }
name = "expires_at"
ty = "DateTime"
storage_ty = { DateTime = 6 }

[[schema.tables.columns]]
id = { table = 8, index = 4 }
name = "date_created"
ty = "DateTime"
storage_ty = { DateTime = 6 }

[[schema.tables.columns]]
id = { table = 8, index = 5 }
name = "date_updated"
ty = "DateTime"
storage_ty = { DateTime = 6 }

[[schema.tables.indices]]
id = { table = 8, index = 0 }
name = "index_blacklisted_tokens_by_id"
on = 8
columns = [{ column = { table = 8, index = 0 }, op = "Eq", scope = "Partition" }]
unique = true
primary_key = true

[[schema.tables.indices]]
id = { table = 8, index = 1 }
name = "index_blacklisted_tokens_by_jti"
on = 8
columns = [{ column = { table = 8, index = 1 }, op = "Eq", scope = "Partition" }]
unique = true
