use jiff::civil::DateTime;
use serde_json::Value;
use toasty::stmt::Json;
use uuid::Uuid;

use crate::models::{WorkflowTaskState, now};

pub struct CreateWorkflowTaskStateParams {
    pub workflow_task_id: Uuid,
    pub workflow_state_id: Uuid,
    pub status: String,
    /// The secret the task's endpoint sends back to report this step done.
    /// Generated by the caller, never derived from anything guessable.
    pub callback_token: String,
}

#[derive(Default)]
pub struct UpdateWorkflowTaskStateParams {
    pub status: Option<String>,
    pub result: Option<Value>,
    pub retry_attempts: Option<i32>,
    pub start_time: Option<DateTime>,
    pub end_time: Option<DateTime>,
}

pub struct WorkflowTaskStateRepository;

impl WorkflowTaskStateRepository {
    pub async fn create(
        &self,
        db: &mut toasty::Db,
        params: CreateWorkflowTaskStateParams,
    ) -> Result<WorkflowTaskState, toasty::Error> {
        let timestamp = now();
        toasty::create!(WorkflowTaskState {
            workflow_task_id: params.workflow_task_id,
            workflow_state_id: params.workflow_state_id,
            status: params.status,
            retry_attempts: 0,
            callback_token: params.callback_token,
            date_created: timestamp,
            date_updated: timestamp,
        })
        .exec(db)
        .await
    }

    pub async fn find_by_id(
        &self,
        db: &mut toasty::Db,
        id: Uuid,
    ) -> Result<Option<WorkflowTaskState>, toasty::Error> {
        WorkflowTaskState::filter(WorkflowTaskState::fields().id().eq(id))
            .first()
            .exec(db)
            .await
    }

    /// Looks a step up by the secret its endpoint presents on callback.
    ///
    /// Whether the token is still valid to redeem is the caller's decision, not
    /// this method's. Finding the row is not the same as accepting the callback.
    pub async fn find_by_callback_token(
        &self,
        db: &mut toasty::Db,
        callback_token: &str,
    ) -> Result<Option<WorkflowTaskState>, toasty::Error> {
        WorkflowTaskState::filter(
            WorkflowTaskState::fields()
                .callback_token()
                .eq(callback_token),
        )
        .first()
        .exec(db)
        .await
    }

    /// Every step's state within one run.
    pub async fn find_by_workflow_state_id(
        &self,
        db: &mut toasty::Db,
        workflow_state_id: Uuid,
    ) -> Result<Vec<WorkflowTaskState>, toasty::Error> {
        WorkflowTaskState::filter(
            WorkflowTaskState::fields()
                .workflow_state_id()
                .eq(workflow_state_id),
        )
        .exec(db)
        .await
    }

    pub async fn update(
        &self,
        db: &mut toasty::Db,
        state: &mut WorkflowTaskState,
        params: UpdateWorkflowTaskStateParams,
    ) -> Result<(), toasty::Error> {
        let mut stmt = toasty::update!(state {
            date_updated: now()
        });
        if let Some(status) = params.status {
            stmt = stmt.status(status);
        }
        if let Some(result) = params.result {
            stmt = stmt.result(Json(result));
        }
        if let Some(retry_attempts) = params.retry_attempts {
            stmt = stmt.retry_attempts(retry_attempts);
        }
        if let Some(start_time) = params.start_time {
            stmt = stmt.start_time(start_time);
        }
        if let Some(end_time) = params.end_time {
            stmt = stmt.end_time(end_time);
        }
        stmt.exec(db).await
    }

    pub async fn delete(&self, db: &mut toasty::Db, id: Uuid) -> Result<(), toasty::Error> {
        WorkflowTaskState::filter(WorkflowTaskState::fields().id().eq(id))
            .delete()
            .exec(db)
            .await
    }
}
