CREATE TABLE "workflow_task_states" (
    "id" UUID NOT NULL,
    "workflow_task_id" UUID NOT NULL,
    "workflow_state_id" UUID NOT NULL,
    "result" TEXT,
    "status" TEXT NOT NULL,
    "retry_attempts" INTEGER NOT NULL,
    "callback_token" TEXT NOT NULL,
    "start_time" TIMESTAMP(6),
    "end_time" TIMESTAMP(6),
    "date_created" TIMESTAMP(6) NOT NULL,
    "date_updated" TIMESTAMP(6) NOT NULL,
    PRIMARY KEY ("id")
);
CREATE INDEX "index_workflow_task_states_by_workflow_task_id" ON "workflow_task_states" ("workflow_task_id");
CREATE INDEX "index_workflow_task_states_by_workflow_state_id" ON "workflow_task_states" ("workflow_state_id");
CREATE UNIQUE INDEX "index_workflow_task_states_by_callback_token" ON "workflow_task_states" ("callback_token");
CREATE TABLE "blacklisted_tokens" (
    "id" BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "jti" TEXT NOT NULL,
    "token_type" TEXT NOT NULL,
    "expires_at" TIMESTAMP(6) NOT NULL,
    "date_created" TIMESTAMP(6) NOT NULL,
    "date_updated" TIMESTAMP(6) NOT NULL,
    PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX "index_blacklisted_tokens_by_jti" ON "blacklisted_tokens" ("jti");
CREATE TABLE "workflow_states" (
    "id" UUID NOT NULL,
    "workflow_id" UUID NOT NULL,
    "status" TEXT NOT NULL,
    "start_time" TIMESTAMP(6),
    "end_time" TIMESTAMP(6),
    "date_created" TIMESTAMP(6) NOT NULL,
    "date_updated" TIMESTAMP(6) NOT NULL,
    PRIMARY KEY ("id")
);
CREATE INDEX "index_workflow_states_by_workflow_id" ON "workflow_states" ("workflow_id");
CREATE TABLE "workflows" (
    "id" UUID NOT NULL,
    "user_id" UUID NOT NULL,
    "name" TEXT NOT NULL,
    "description" TEXT,
    "run_type" TEXT NOT NULL,
    "schedule_time" TIMESTAMP(6),
    "cron_expression" TEXT,
    "cron_next_run" TIMESTAMP(6),
    "is_active" BOOLEAN NOT NULL,
    "date_created" TIMESTAMP(6) NOT NULL,
    "date_updated" TIMESTAMP(6) NOT NULL,
    PRIMARY KEY ("id")
);
CREATE INDEX "index_workflows_by_user_id" ON "workflows" ("user_id");
CREATE TABLE "users" (
    "id" UUID NOT NULL,
    "username" TEXT NOT NULL,
    "email" TEXT NOT NULL,
    "email_verified" BOOLEAN NOT NULL,
    "password_hash" TEXT NOT NULL,
    "date_created" TIMESTAMP(6) NOT NULL,
    "date_updated" TIMESTAMP(6) NOT NULL,
    "date_joined" TIMESTAMP(6) NOT NULL,
    PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX "index_users_by_email" ON "users" ("email");
CREATE TABLE "workflow_task_edges" (
    "id" UUID NOT NULL,
    "workflow_id" UUID NOT NULL,
    "from_task_id" UUID NOT NULL,
    "to_task_id" UUID NOT NULL,
    "date_created" TIMESTAMP(6) NOT NULL,
    "date_updated" TIMESTAMP(6) NOT NULL,
    PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX "index_workflow_task_edges_by_workflow_id_and_from_task_id__5f9d" ON "workflow_task_edges" ("workflow_id", "from_task_id", "to_task_id");
CREATE INDEX "index_workflow_task_edges_by_workflow_id" ON "workflow_task_edges" ("workflow_id");
CREATE INDEX "index_workflow_task_edges_by_from_task_id" ON "workflow_task_edges" ("from_task_id");
CREATE INDEX "index_workflow_task_edges_by_to_task_id" ON "workflow_task_edges" ("to_task_id");
CREATE TABLE "tasks" (
    "id" UUID NOT NULL,
    "user_id" UUID NOT NULL,
    "name" TEXT NOT NULL,
    "description" TEXT,
    "endpoint" TEXT NOT NULL,
    "method" TEXT NOT NULL,
    "result_schema" TEXT,
    "body" TEXT,
    "date_created" TIMESTAMP(6) NOT NULL,
    "date_updated" TIMESTAMP(6) NOT NULL,
    PRIMARY KEY ("id")
);
CREATE INDEX "index_tasks_by_user_id" ON "tasks" ("user_id");
CREATE TABLE "user_verifications" (
    "id" BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "user_id" UUID NOT NULL,
    "code" TEXT NOT NULL,
    "expires_at" TIMESTAMP(6) NOT NULL,
    "date_created" TIMESTAMP(6) NOT NULL,
    "date_updated" TIMESTAMP(6) NOT NULL,
    PRIMARY KEY ("id")
);
CREATE INDEX "index_user_verifications_by_user_id" ON "user_verifications" ("user_id");
CREATE UNIQUE INDEX "index_user_verifications_by_code" ON "user_verifications" ("code");
CREATE TABLE "workflow_tasks" (
    "id" UUID NOT NULL,
    "workflow_id" UUID NOT NULL,
    "task_id" UUID NOT NULL,
    "step_name" TEXT NOT NULL,
    "task_body" TEXT,
    "task_result_schema" TEXT,
    "run_position" INTEGER NOT NULL,
    "retry_count" INTEGER,
    "retry_delay_secs" INTEGER,
    "date_created" TIMESTAMP(6) NOT NULL,
    "date_updated" TIMESTAMP(6) NOT NULL,
    PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX "index_workflow_tasks_by_workflow_id_and_step_name" ON "workflow_tasks" ("workflow_id", "step_name");
CREATE INDEX "index_workflow_tasks_by_workflow_id" ON "workflow_tasks" ("workflow_id");
CREATE INDEX "index_workflow_tasks_by_task_id" ON "workflow_tasks" ("task_id");
