[package]
name = "api"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4"
sea-orm = { version = "2.0.0-rc", features = [ "sqlx-postgres", "runtime-tokio-native-tls", "with-chrono", "with-uuid", "macros", "debug-print", "mock",  "schema-sync", "entity-registry"] }
uuid = { version = "1", features = ["v7", "v4"] }
chrono = "0.4"
serde = { version = "1.0", features = ["derive"] }
either = "1.15.0"
bcrypt = "0.19.0"
dotenvy = "0.15.7"
actix-http = "3.12.1"
serde_json = "1.0.149"
rand = "0.10.1"
jsonwebtoken = {version = "10.3.0", features = ["aws_lc_rs"]}
futures-util = "0.3"